export const Users = [
    {
      id:1,
      profilePicture: "assets/1.PNG",
      username: "Grandon Batlin",
    },
    {
      id:2,
      profilePicture: "assets/2.PNG",
      username: "Pames Joulin",
    },
    {
      id:3,
      profilePicture: "assets/3.PNG",
      username: "Zsvaldo Oavaleta",
    },
    {
      id:4,
      profilePicture: "assets/4.PNG",
      username: "Muchos Ralvados ",
    },
    {
      id:5,
      profilePicture: "assets/5.PNG",
      username: "Hist Maker",
    },
    {
      id:6,
      profilePicture: "assets/6.PNG",
      username: "Aack Znderson",
    },
    {
      id:7,
      profilePicture: "assets/7.jpg",
      username: "Space Cat",
    },
    {
      id:8,
      profilePicture: "assets/8.jpg",
      username: "BAMA FAN",
    },
    {
      id:9,
      profilePicture: "assets/9.jpg",
      username: "Navy Guy",
    },
    {
      id:10,
      profilePicture: "assets/10.jpg",
      username: "Shady Beard",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "So helpful",
      photo: "assets/11.png",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      photo: "assets/12.png",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Not gonna get me",
      photo: "assets/13.png",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      photo: "assets/14.PNG",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      photo: "assets/15.png",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      photo: "assets/6.PNG",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Never regret anything that made you smile.",
      photo: "assets/7.jpg",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      photo: "assets/8.jpg",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "Change the world with github.",
      photo: "assets/ad.jpg",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      photo: "assets/10.jpg",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];